# To works need download the Feather Server API from:
# https://github.com/FeatherMC/feather-server-api/releases
#
# The full list of mods can be found at:
# https://docs.feathermc.com/server-api/mods

blocked-mods:
  - culllogs
  - nickHider
  - armorStatus
